// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izymayczjppcgmejqxus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eW1heWN6anBwY2dtZWpxeHVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTM3MzcsImV4cCI6MjA3MDY2OTczN30.pVizQK0SLN8tNDvTlzknlVhb19U4hyPnLQ8BCFkK-8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});